# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
